@startuml

!theme plain
hide empty methods

!procedure $schema($name, $slug)
package "$name" as $slug <<Rectangle>>
!endprocedure

!procedure $table($name, $slug)
entity "<b>$name</b>" as $slug << (T, Orange) table >>
!endprocedure

!procedure $view($name, $slug)
entity "<b>$name</b>" as $slug << (V, Aquamarine) view >>
!endprocedure

!procedure $pk($name)
<color:#GoldenRod><&key></color> <b>$name</b>
!endprocedure

!procedure $fk($name)
<color:#Silver><&key></color> $name
!endprocedure

!procedure $column($name)
{field} <color:#White><&media-record></color> $name
!endprocedure


title "ANIPHOTO DOMAIN MODEL DIAGRAM"

$schema("ANIPHOTO", "id_12345678") {

  $table("User", "id_abcdef01") {
    $pk("id"): INTEGER NOT NULL
    $column("username"): VARCHAR
    $column("hashPassword"): VARCHAR
    $column("email"): VARCHAR
    $column("registeredAt"): DATE
  }

  $table("Photo", "id_abcdef02") {
    $pk("id"): INTEGER NOT NULL
    $column("originalId"): INTEGER 
    $column("title"): VARCHAR
    $column("imageUrl"): VARCHAR
    $column("createdAt"): DATE
    $fk("createdBy"): INTEGER NOT NULL
  }

  $table("Model", "id_abcdef04") {
    $pk("id"): INTEGER NOT NULL
    $column("name"): VARCHAR
    $column("title"): VARCHAR
    $column("description"): VARCHAR
    $column("previewUrl"): VARCHAR
  }

  $table("PhotoModel", "id_abcdef06") {
    $fk("photoId"): INTEGER NOT NULL
    $fk("modelId"): INTEGER NOT NULL
  }

  id_abcdef01 --{ id_abcdef02 : owns
  id_abcdef02 --{ id_abcdef06 : hasTags

}

@enduml