@startuml "ANIPHOTO DOMAIN MODEL DIAGRAM"
    class User {
        +id: Integer
        +username: String
        +hashPassword: String
        +email: String
        +registeredAt: Date
    }

    class Photo {
        +id: Integer
        +originalId: Integer
        +title: String
        +imageUrl: String
        +createdAt: Date
        +createdBy: User
    }

    class Model {
        +id: Integer
        +name: String
        +title: String
        +description: String
        +previewUrl: String
    }

    User "1" -- "*" Photo : owns
    Photo "1" -- "*" Model : hasModel
@enduml