@startuml "ANIPHOTO USE CASE DIAGRAM"
    left to right direction

    rectangle "Aniphoto IOS Application" {
        actor "User" as user
        (Explore effects) as (Explore)
        (Import photos) as (Import)
        (Share photos) as (Share)

        user --down-> (Login)
        user --down-> (Logout)

        user --down-> (Explore)
        user --down-> (Import)
        user --down-> (Generate photos)
        user --down-> (View photos)
        user --down-> (Share)
        user --down-> (Setting)

        actor "Admin" as admin
        admin --down-> (Block user)
        admin --down-> (See activity log of users)
    }

@enduml